### ISSUE TITLE
Casino 2 does not play nice with membership names with spaces

### ISSUE THREAD

**Issue by jjay12365** [Redjumpman/Jumper-Plugins#105]
**Note: for support questions, please use the [Cog Support Server](https://discord.gg/c6HQUb7)**. This repository's issues are reserved for feature requests and bug reports.

# I'm submitting a ...
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

# **Cog Information**

Name:  Casino
Version: 2.0.4

# Bug Report
**Screenshot of console: (If Applicable)**
Console Not Applicable But Discord commands used:
![9ce349afd89482abd351acf3a837c47f](https://user-images.githubusercontent.com/22643403/36637358-78e61382-19a8-11e8-8dba-6756cef9caa5.png)

**Command used:**
[p]casino assignmem

**Expected result:**
ASSASSIN0831 (224214882420129792) manually assigned ASSASSIN0831 (224214882420129792) the Tier 2 membership.

**Steps to reproduce:**
Try to assign a membership with a space in the name

**Please tell me about your environment/OS:**
Windows Sever 2016 Virtual machine using Amazon's AWS 1 GB of Ram

**Comment by Redjumpman** [comment]
Data cannot be saved using spaces, so they have to be converted to underscores. As a result, I need to make allowances for this. I'll post a fix for this soon. Thanks for posting.

**Comment by jjay12365** [comment]
I also can't delete them

**Comment by Redjumpman** [comment]
I made a mistake in the creation process, which kinda makes the memberships messed up. I'm fixing that part, and I'm adding a way to clear all of your memberships via `[p]casino resetinstance`. I'm just testing it now to make sure it works.

**Comment by Redjumpman** [comment]
This should be fixed in Casino hotfix 2.0.5. Make sure you update to the latest version. When you do, use the command `[p]casino resetinstance` and choose memberships. You will have to create the membership again (sorry about that), but it should work now. create, delete, edit, and displaying memberships should all work as intended as well. I'll keep this open incase it doesn't fix it for you.

**Comment by jjay12365** [comment]
![fd0d3d334b9bfcdf147e513e50ed510e](https://user-images.githubusercontent.com/22643403/36637988-c63190e6-19b5-11e8-9e4c-83e0f1b74b96.png)

It allowed me to manually add the role but it doesn't work 100%. you need access level 1 to play the games but when I manually add the membership it still says I have access level 0 after saying I manually added a membership successfully Problem may lie in the data. I noticed it saves memberships with an _ but not when it shows when a person has it assigned as shown in the picture.

**Comment by Redjumpman** [comment]
Try updating casino again, revoking the membership, and then adding it again. I just pushed another update.

**Comment by jjay12365** [comment]
Ok it now adds the membership and allows me to play but when I revoke the membership it doesn't set my access back to 0. The setting file shows I have the membership just not assigned anymore. In the photo the requirement is 100k credits but I only have 10k so it's not because it auto gave me the roll. I also reset all using [p]casino resetinstance but the files still show memberships are given to people even though the membership doesn't exist

![ff4829a6ccefc8fb5b6f2aeedcd9bcf2](https://user-images.githubusercontent.com/22643403/36638290-1b72227e-19bf-11e8-8729-c03aced665e0.png)

**Comment by Redjumpman** [comment]
When you revoke a membership it should say **It will calculate the appropriate membership during the next cycle.** This takes 5 minutes. At that point it will re-evaluate your membership. I just ran a test, so I know this work. If you have a separate issue or the same come up, create another issue. Since the initial problem is fixed, I'm closing this specific issue.
